### ISSUE TITLE
viroprofiler` currently is sticked on revision

### ISSUE THREAD

**Issue by RazaRaza** [deng-lab/viroprofiler#1]
### Description of the bug

I am trying to install viroprofiler, but I am stuck. I have tried -r option too, but it is not working. 

N E X T F L O W  ~  version 21.10.6
Project `deng-lab/viroprofiler` currently is sticked on revision: main -- you need to specify explicitly a revision with the option `-r` to use it

**Comment by rujinlong** [comment]
Hi @RazaRaza , could you paste your full command here?
