### ISSUE TITLE
Process requirement exceeds available memory

### ISSUE THREAD

**Issue by olgais93** [deng-lab/viroprofiler#3]
I'm getting an error when running Viroprofiler, saying that process requirements exceed available memory. Is there any way I can run Viroprofiler on a system that has <90GB memory?

I ran this: 
`nextflow run deng-lab/viroprofiler --input samplesheet.csv -profile singularity  -r v0.1`

And got this error: 
`Process requirement exceeds available memory -- req: 90 GB; avail: 62.7 GB`

I tried running: 
`nextflow run deng-lab/viroprofiler  --input samplesheet.csv     -profile singularity -r v0.1 --max_memory "20.GB" --max_cpus "2"`

But got the same error.

**Comment by rujinlong** [comment]
Hi @olgais93 ,

It seems there is a bug in the `--max_memory` parameter. I will check and fix it in the next release. Before that, you can download the [custom config file](https://github.com/deng-lab/viroprofiler/blob/main/custom.config) and modify cpu and memory parameters for each step in the file, and then run the pipeline with additional `-c custom.config` parameter.

Please let me know if this helps.
