### ISSUE TITLE
OCI index found, but accept header does not support OCI indexes

### ISSUE THREAD

**Issue by liuronghyw** [deng-lab/viroprofiler#4]
### Description of the bug

Dear developers:
      I can't pull the viroprofilter in cluster with UNIX operate system, the command  as follows:

export NXF_SINGULARITY_CACHEDIR="./temp"

nextflow run deng-lab/viroprofiler -profile singularity --mode "setup" -r v0.2 --db "/public/home/**/db/viroprofiler" -without-conda

The error is as follows:
![image](https://user-images.githubusercontent.com/42331632/231637753-f4ecce7a-1134-4a37-be7d-e6546fc9754c.png)

Would you please give me some suggestions on how to solve this problem. 

### Command used and terminal output

```console
nextflow run deng-lab/viroprofiler -profile singularity --mode "setup" -r v0.2 --db "/public/home/hpc4011032/db/viroprofiler"
```

### System information

N E X T F L O W  ~  version 22.10.6

HPC
local 
Signalarity
CentOS Linux

viroprofiler v0.2

**Comment by rujinlong** [comment]
Hi @liuronghyw, could you try the following command and then report the output?

```
singularity pull denglab-viroprofiler-base-v0.2.img docker://denglab/viroprofiler-base:v0.2
```

**Comment by liuronghyw** [comment]
Hi, Dr. long.  I can pull the image with your command.  Since I am not familiar with Nextflow. Would you please tell me how to bulid the pipeline with local image (denglan-viroprofilter-base-v0.2)？ Thank you very much!

**Comment by rujinlong** [comment]
I guess the original error occurred because I released the new version 10 hours ago, and you executed the Nextflow command simultaneously while the image was not yet successfully created. If you run the Nextflow command now, the error should not occur. Alternatively, you can pull images manually using the following commands, and then execute the Nextflow command:

```
singularity pull denglab-viroprofiler-base-v0.2.img docker://denglab/viroprofiler-base:v0.2
singularity pull denglab-viroprofiler-vibrant-v0.2.img docker://denglab/viroprofiler-vibrant:v0.2
singularity pull denglab-viroprofiler-binning-v0.2.img docker://denglab/viroprofiler-binning:v0.2
singularity pull denglab-viroprofiler-host-v0.2.img docker://denglab/viroprofiler-host:v0.2
singularity pull denglab-viroprofiler-geneannot-v0.2.img docker://denglab/viroprofiler-geneannot:v0.2
singularity pull denglab-viroprofiler-taxa-v0.2.img docker://denglab/viroprofiler-taxa:v0.2
singularity pull denglab-viroprofiler-abundance-v0.2.img docker://denglab/viroprofiler-abundance:v0.2
singularity pull denglab-viroprofiler-bracken-v0.2.img docker://denglab/viroprofiler-bracken:v0.2
singularity pull denglab-viroprofiler-replicyc-v0.2.img docker://denglab/viroprofiler-replicyc:v0.2
```

**Comment by rujinlong** [comment]
What is the version of singularity? Could you try the following command to update the pipeline,

```
nextflow pull deng-lab/viroprofiler
```

and then run with the `-r main` parameter,

```
nextflow run deng-lab/viroprofiler -profile singularity --mode "setup" -r main --db "/public/home/hpc4011032/db/viroprofiler"
```

**Comment by rujinlong** [comment]
Could you please paste the first two lines of the output here? it should look like the following,

```
N E X T F L O W  ~  version 22.04.0
Launching `https://github.com/deng-lab/viroprofiler` [soggy_elion] DSL2 - revision: 471c32e0ba [main]
```

**Comment by rujinlong** [comment]
It's quite strange. The error seems to be caused by singularity. I cannot reproduce this error, but if you can provide additional information, it may help me identify the bug. Could you try as the following,

1. Pull the image manually using [this](https://github.com/deng-lab/viroprofiler/issues/4#issuecomment-1506402054) command.
2. If it fails, check the singularity version and path using
```
singularity --version
which singularity
```
and paste the output here.

**Comment by olgais93** [comment]
The first thing failed and gave this error:
```
$ singularity pull denglab-viroprofiler-base-v0.2.img docker://denglab/viroprofiler-base:v0.2
ERROR: pull is only supported for shub URIs
```
Singularity version and path:
```
$ singularity --version
2.4.2-dist
$ which singularity
/home/olga/miniconda3/bin/singularity
```

**Comment by rujinlong** [comment]
Ok, this might be the reason. Your singularity version is quite old. Could you update to the newest version? The latest on conda is singularity v3.8.7 and singularityce v3.10.0. If possible, ask your sys-admin to install the newest singularity as root, as explained in another issue https://github.com/darcyabjones/pante/issues/4#issuecomment-546830722

**Comment by olgais93** [comment]
I installed a newer version of Singularity. 
```
$ singularity --version
singularity-ce version 3.11.1-jammy
```
It is now giving a different error: 

`$ nextflow run deng-lab/viroprofiler -profile singularity --mode "setup" -r main`

  ```
WorkflowError:
  Failed to solve the job scheduling problem with pulp. Please report a bug and use --scheduler greedy as a workaround:
  Pulp: Error while trying to execute, use msg=True for more detailscbc
  [2023-04-13 19:49 CRITICAL] Command 'snakemake --snakefile /opt/conda/envs/viroprofiler-virsorter2/lib/python3.10/site-packages/virsorter/rules/setup-retry.smk --directory /home/olga/viroprofiler/virsorter2 --quiet --config Skip_deps_install=False --jobs 1 --rerun-incomplete --latency-wait 600 --nolock  --use-conda --conda-prefix /home/olga/viroprofiler/virsorter2/conda_envs --conda-frontend mamba ' returned non-zero exit status 1.

Work dir:
  /home/olga/work/b9/26db2d6609386b7de7b34fa9ee8433

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```
Thank you very much

**Comment by rujinlong** [comment]
It seems this is a bug in virsorter2 and caused by snakemake https://github.com/jiarong/VirSorter2/issues/51. I updated the code, please try the following commands,

```bash
# update the pipeline
nextflow pull deng-lab/viroprofiler

# delete the old virsorter2 database (in your case, /home/olga/viroprofiler/virsorter2)
rm -rf /path/to/viroprofiler/db/virsorter2

# run the pipeline
nextflow run deng-lab/viroprofiler -profile singularity --mode "setup" -r main
```

**Comment by rujinlong** [comment]
There is a log file in `work/f5/24a9a1*/.command.log`, could show me the content of that file?

**Comment by olgais93** [comment]
In  `/home/olga/work/f5/24a9a1c9f030cba84ff25d0ee074cc/.command.log`, there was this: 

`Pblm, I could not find directory /home/olga/viroprofiler/iphop/Sept_2021_pub. Maybe the host database directory was not specified with the --db_dir and is not the default "db/" directory ?`

**Comment by rujinlong** [comment]
Your previous setup of the iphop database is not complete. The complete iphop database is ~200G. Please delete the iphop folder, and then run the setup step again, or you can use the `--use_iphop false` parameter to skip the host prediction step.
